[tool.ruff]
target-version = "py38"
line-length = 100

[tool.ruff.lint]
select = [
    "E",  # Error
    "W",  # Warning
    "F",  # pyflakes
    "I",  # isort
]
fixable = ["ALL"]
extend-select = ["E501"]  # Line too long