

# summary changes for files based diff
# diff => {__DIFF__}
PROMPT_SUMMARY_FOR_FILES = """ 
I have made the following changes: 
```{__DIFF__}```
Please provide a summary for each modified file. The output should ONLY be a JSON format like: 
{"file1": "Summary of the changes made in file1", 
"file2": "Summary of the changes made in file2"}
Key is real filename which is exist in diff changes.
Please make sure there is no other additional output.
"""
prompt_summary_for_files_llm_config = {
	"model": "gpt-3.5-turbo-16k"
}
# ask summaries for missed files
# missed files => {__MISSED_FILES__}
PROMPT_SUMMARY_FOR_FILES_RETRY = """
The following files are missed in your summary:
{__MISSED_FILES__}
"""

# group changes for files based diff
# diff => {__DIFF__}
PROMPT_GROUP_FILES = """
Please group the following modified files based on their modification relevance:
{__DIFF__}
The output should be a JSON format like:
[
	{"files": ["file1", "file2"], "group": "Feature Improvement", "important_level": 1},
	{"files": ["file3"], "group": "Bug Fix", "important_level": 2}
]
Please make sure there is no other additional output.
Please make sure every file in diff is grouped.
important_level is an integer from 1 to 10, 1 means the most important, 10 means the least important.
"""
prompt_group_files_llm_config = {
	"model": "gpt-3.5-turbo-16k"
}
# re-group files based missed files
# missed files => {__MISSED_FILES__}
PROMPT_GROUP_FILES_RETRY = """
The following files are missed in your response:
{__MISSED_FILES__}
Please re-group the files again, don't miss any file.
"""


# generate commit message based diff and user_input
# diff => {__DIFF__}
# user_input => {__USER_INPUT__}
PROMPT_COMMIT_MESSAGE_BY_DIFF_USER_INPUT = """
I have made the following changes to the code:
```
{__DIFF__}
```
Please help me generate a commit message. {__USER_INPUT__}. If you don't know exact closed issue number, please don't output "Closes #Issue_number" line. The format is as follows:
```
feat: commit message title

Commit message body:
- Detailed message 1.
- Detailed message 2.

Closes #Issue_number
```
Adhere to best practices. Keep the title under 50 characters and each body line under 72 characters.
"""
prompt_commit_message_by_diff_user_input_llm_config = {
	"model": "gpt-3.5-turbo-16k"
}

# generate commit message based file summary and user_input
# file_summary => {__FILE_SUMMARY__}
# user_input => {__USER_INPUT__}
PROMPT_COMMIT_MESSAGE_BY_SUMMARY_USER_INPUT = """
Here are the file summaries generated by AI:
```
{__FILE_SUMMARY__}
```

Please help me generate a commit message. {__USER_INPUT__}. If you don't know exact closed issue number, please don't output "Closes #Issue_number" line. The format is as follows:
```
feat: commit message title

Commit message body:
- Detailed message 1.
- Detailed message 2.

Closes #Issue_number
```
Adhere to best practices. Keep the title under 50 characters and each body line under 72 characters.
"""
prompt_commit_message_by_summary_user_input_llm_config = {
	"model": "gpt-3.5-turbo-16k"
}
