name: Sync to GitLab

on:
  push:
    branches:
      - main
      - scripts

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config user.name "gh-action"
          git config user.email "gh-action@merico.dev"

      - name: Add GitLab remote
        run: |
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_ACCESS_TOKEN }}@gitlab.com/devchat-ai/workflows.git

      - name: Retry Command
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: |
            git fetch gitlab &&
            git push gitlab --force $GITHUB_REF_NAME:$GITHUB_REF_NAME
